/*
 * Copyright (C) 2020 BlueKitchen GmbH
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holders nor the names of
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 * 4. Any redistribution, use, or modification is done solely for
 *    personal benefit and not for any commercial purpose or for
 *    monetary gain.
 *
 * THIS SOFTWARE IS PROVIDED BY BLUEKITCHEN GMBH AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL BLUEKITCHEN
 * GMBH OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
 * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * Please inquire about commercial licensing options at
 * contact@bluekitchen-gmbh.com
 *
 */

#define BTSTACK_FILE__ "hog_host_demo.c"

/*
 * hog_host_demo.c
 */

/* EXAMPLE_START(hog_host_demo): HID Host LE
 *
 * @text This example implements a minimal HID-over-GATT Host. It scans for LE HID devices, connects to it,
 * discovers the Characteristics relevant for the HID Service and enables Notifications on them.
 * It then dumps all Boot Keyboard and Mouse Input Reports
 */

#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <btstack_tlv.h>

#include "btstack_config.h"
#include "btstack.h"
#include "pico/cyw43_arch.h"
#include "pico/multicore.h"
#include "pico/stdlib.h"
#include "ble_host.h"
#include "ble_bridge.h"

// ble_gatt.gatt contains the declaration of the provided GATT Services + Characteristics
// ble_gatt.h    contains the binary representation of ble_gatt.gatt
// it is generated by the build system by calling: $BTSTACK_ROOT/tool/compile_gatt.py ble_gatt.gatt ble_gatt.h
// it needs to be regenerated when the GATT Database declared in the .gatt file is modified
#include "ble_gatt.h"

// TAG to store remote device address and type in TLV
#define TLV_TAG_HOGD ((((uint32_t) 'H') << 24 ) | (((uint32_t) 'O') << 16) | (((uint32_t) 'G') << 8) | 'D')

typedef struct {
    bd_addr_t addr;
    bd_addr_type_t addr_type;
} le_device_addr_t;

static enum {
    W4_WORKING,
    W4_HID_DEVICE_FOUND,
    W4_CONNECTED,
    W4_ENCRYPTED,
    W4_HID_CLIENT_CONNECTED,
    READY,
    W4_TIMEOUT_THEN_SCAN,
    W4_TIMEOUT_THEN_RECONNECT,
} app_state;

static le_device_addr_t remote_device;
static hci_con_handle_t connection_handle;
static uint16_t hids_cid;
static hid_protocol_mode_t protocol_mode = HID_PROTOCOL_MODE_REPORT;

// SDP
static uint8_t hid_descriptor_storage[500];

/* ---- WHICH DEVICE DO WE CONNECT TO? ------------------------------------------------------
   The BTstack example connects to the first advertiser that carries the HID service UUID
   (0x1812). On a real desk that is close to useless: a scan here saw 7 BLE devices and only
   ONE set the flag -- a stranger's keyboard -- while every device the user actually owns,
   including a HID remote that works fine with a phone, advertised hid=0.

   So: if a TARGET ADDRESS is set we connect to exactly that device and ignore the flag. This
   is the general mechanism -- the web tool will scan, show you the list (address + name +
   RSSI), and set the target to whichever device you pick. It is not specific to any product.

   BLE_TARGET_ADDR can be set at build time, e.g.
       -DBLE_TARGET_ADDR="68:FC:CA:B4:43:B7"
   Leave it undefined and the old advertise-HID behaviour applies.                            */
static bd_addr_t target_addr;
static bool target_addr_set = false;

// the advertised name of the device we are connecting to, reported up to the config tool
static char connected_name[32];

static bool ble_has_target_addr(void){
    return target_addr_set;
}

static bool ble_addr_matches_target(const bd_addr_t addr){
    return memcmp(addr, target_addr, sizeof(bd_addr_t)) == 0;
}

void ble_host_set_target_addr(const char * addr_str){
    if ((addr_str == NULL) || (addr_str[0] == 0)) {
        target_addr_set = false;
        return;
    }
    target_addr_set = sscanf_bd_addr(addr_str, target_addr) == 1;
    printf("BLE target address: %s (%s)\n", addr_str, target_addr_set ? "set" : "PARSE FAILED");
}

/* Pull the advertised local name (AD types 0x08 shortened / 0x09 complete) out of a report.
   A MAC address alone tells you nothing about which device is which. */
static void adv_event_get_name(const uint8_t * packet, char * out, uint16_t out_size){
    out[0] = 0;
    const uint8_t * ad_data = gap_event_advertising_report_get_data(packet);
    uint8_t ad_len = gap_event_advertising_report_get_data_length(packet);

    ad_context_t ctx;
    for (ad_iterator_init(&ctx, ad_len, ad_data); ad_iterator_has_more(&ctx); ad_iterator_next(&ctx)){
        uint8_t type = ad_iterator_get_data_type(&ctx);
        if ((type != BLUETOOTH_DATA_TYPE_SHORTENED_LOCAL_NAME) &&
            (type != BLUETOOTH_DATA_TYPE_COMPLETE_LOCAL_NAME)) continue;
        uint8_t size = ad_iterator_get_data_len(&ctx);
        const uint8_t * data = ad_iterator_get_data(&ctx);
        if (size >= out_size) size = out_size - 1;
        memcpy(out, data, size);
        out[size] = 0;
        if (type == BLUETOOTH_DATA_TYPE_COMPLETE_LOCAL_NAME) return;  // prefer the complete name
    }
}

// used to implement connection timeout and reconnect timer
static btstack_timer_source_t connection_timer;

// onboard LED status (Adapt E): solid = connected/ready, fast blink =
// connecting/pairing, slow blink = scanning/idle.
static void ble_clear_all_bonds(void);
static void hog_start_scan(void);
static void hog_start_connect(void);

/* PAIRING MODE.
 *
 * Off by default. While off, the remapper ONLY reconnects to the device it already knows, and will
 * not bond with anything else -- so an absent remote does not leave it open to the whole room.
 *
 * The config tool's "Pair new device" button opens a WINDOW: for PAIRING_WINDOW_MS we scan and will
 * accept a new device. The window closes as soon as one is paired, or when it times out -- it never
 * stays open. */
#define PAIRING_WINDOW_MS 180000   // 3 minutes: long enough to go and wake the remote

static bool pairing_mode = false;
static btstack_timer_source_t pairing_timer;

static void pairing_window_expired(btstack_timer_source_t * ts){
    UNUSED(ts);
    if (!pairing_mode) return;
    pairing_mode = false;
    printf("\nPairing window closed (nothing paired). Not pairable again until you ask.\n");
    gap_stop_scan();
    hog_start_connect();   // fall back to the remembered device, or go idle
}

static void ble_enter_pairing_mode(void){
    pairing_mode = true;
    printf("PAIRING MODE OPEN for %d s -- the next BLE HID device found will be paired.\n",
           PAIRING_WINDOW_MS / 1000);
    btstack_run_loop_remove_timer(&pairing_timer);
    btstack_run_loop_set_timer(&pairing_timer, PAIRING_WINDOW_MS);
    btstack_run_loop_set_timer_handler(&pairing_timer, &pairing_window_expired);
    btstack_run_loop_add_timer(&pairing_timer);
}

static void ble_exit_pairing_mode(void){
    if (!pairing_mode) return;
    pairing_mode = false;
    btstack_run_loop_remove_timer(&pairing_timer);
    printf("Paired. Pairing mode closed.\n");
}

/* The config tool's "Pair new device" / "Clear bonds" buttons land on CORE 0 as config commands
   12/13. BTstack may only be touched from core 1, so core 0 raises a flag in the bridge and we
   pick it up here, inside BTstack's own run loop. Polled from the LED timer, which already ticks
   every 100ms -- no extra timer, and a 100ms latency on a button press is invisible. */
static void ble_handle_core0_requests(void){
    uint32_t req = ble_bridge_take_requests();
    if (req == 0) return;

    if (req & BLE_REQ_CLEAR_BONDS){
        printf("\n== CLEAR BONDS (from the config tool) ==\n");
        ble_clear_all_bonds();
    }
    if (req & BLE_REQ_PAIR_NEW){
        printf("\n== PAIR NEW DEVICE (from the config tool) ==\n");
        // Forget the device we are on, so we stop reconnecting to it and go looking again.
        if (target_addr_set) {
            target_addr_set = false;   // a new pairing should not be pinned to the old address
        }
        ble_clear_all_bonds();
    }

    // Drop the link and start over. The disconnect handler restarts the scan; if we were not
    // connected, start it here.
    if (connection_handle != HCI_CON_HANDLE_INVALID){
        app_state = W4_TIMEOUT_THEN_SCAN;
        gap_disconnect(connection_handle);
    } else {
        hog_start_connect();   // NOT _scan: that would make us pairable again
    }
}

static btstack_timer_source_t led_timer;
static void led_timer_handler(btstack_timer_source_t * ts){
    static uint32_t tick = 0;
    tick++;

    ble_handle_core0_requests();

    /* THE LED IS THE ONLY STATUS CHANNEL ON THIS BUILD (no USB serial -- we are a HID device), so
       every state MUST look different. It used to lump "idle, not pairable" and "scanning for your
       remote" into the same slow blink, which made it impossible to tell whether a pairing request
       had even arrived. */
    int on;
    switch (app_state){
        case READY:
            on = 1;                              // SOLID           = connected, reports flowing
            break;
        case W4_CONNECTED:
        case W4_ENCRYPTED:
        case W4_HID_CLIENT_CONNECTED:
            on = tick & 1;                       // FAST BLINK      = connecting / pairing
            break;
        case W4_HID_DEVICE_FOUND:
            // DOUBLE BLINK ("blink-blink ... pause") = PAIRING WINDOW OPEN, actively looking.
            // Unmistakable, and it tells you the button press really did land.
            on = ((tick % 10) == 0) || ((tick % 10) == 2);
            break;
        default:
            // SLOW BLINK = idle / retrying a bonded remote that is not answering (switched off,
            // out of range). Not an error, and NOT a state where we would pair with anything else.
            on = (tick / 5) & 1;
            break;
    }
    cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, on);
    btstack_run_loop_set_timer(ts, 100);
    btstack_run_loop_add_timer(ts);
}

// register for events from HCI/GAP and SM
static btstack_packet_callback_registration_t hci_event_callback_registration;
static btstack_packet_callback_registration_t sm_event_callback_registration;

// used to store remote device in TLV
static const btstack_tlv_t * btstack_tlv_singleton_impl;
static void *                btstack_tlv_singleton_context;

// Simplified US Keyboard with Shift modifier

#define CHAR_ILLEGAL     0xff
#define CHAR_RETURN     '\n'
#define CHAR_ESCAPE      27
#define CHAR_TAB         '\t'
#define CHAR_BACKSPACE   0x7f

/**
 * English (US)
 */
static const uint8_t keytable_us_none [] = {
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /*   0-3 */
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',                   /*  4-13 */
        'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',                   /* 14-23 */
        'u', 'v', 'w', 'x', 'y', 'z',                                       /* 24-29 */
        '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',                   /* 30-39 */
        CHAR_RETURN, CHAR_ESCAPE, CHAR_BACKSPACE, CHAR_TAB, ' ',            /* 40-44 */
        '-', '=', '[', ']', '\\', CHAR_ILLEGAL, ';', '\'', 0x60, ',',       /* 45-54 */
        '.', '/', CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,   /* 55-60 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 61-64 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 65-68 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 69-72 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 73-76 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 77-80 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 81-84 */
        '*', '-', '+', '\n', '1', '2', '3', '4', '5',                       /* 85-97 */
        '6', '7', '8', '9', '0', '.', 0xa7,                                 /* 97-100 */
};

static const uint8_t keytable_us_shift[] = {
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /*  0-3  */
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',                   /*  4-13 */
        'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',                   /* 14-23 */
        'U', 'V', 'W', 'X', 'Y', 'Z',                                       /* 24-29 */
        '!', '@', '#', '$', '%', '^', '&', '*', '(', ')',                   /* 30-39 */
        CHAR_RETURN, CHAR_ESCAPE, CHAR_BACKSPACE, CHAR_TAB, ' ',            /* 40-44 */
        '_', '+', '{', '}', '|', CHAR_ILLEGAL, ':', '"', 0x7E, '<',         /* 45-54 */
        '>', '?', CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,   /* 55-60 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 61-64 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 65-68 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 69-72 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 73-76 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 77-80 */
        CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL, CHAR_ILLEGAL,             /* 81-84 */
        '*', '-', '+', '\n', '1', '2', '3', '4', '5',                       /* 85-97 */
        '6', '7', '8', '9', '0', '.', 0xb1,                                 /* 97-100 */
};



#define NUM_KEYS 6
static uint8_t last_keys[NUM_KEYS];

/* A HID report arrived from the remote. Hand it to core 0, where hid-remapper's engine will run it
   through the mappings and emit it over USB. Do NOT printf here: this is BTstack's run loop, and
   printing every report at 100+/s stalls it and drops the Bluetooth link. */
static void hid_handle_input_report(uint8_t service_index, const uint8_t * report, uint16_t report_len){
    (void) service_index;   // one HID service; the engine keys off the report id in the payload
    ble_bridge_push_report(report, report_len);
}

/**
 * @section Test if advertisement contains HID UUID
 * @param packet
 * @param size
 * @returns true if it does
 */
/* Forget one device: drop its LTK from the bonding db AND the "last connected" tag, so the next
   attempt is a genuine fresh pairing rather than another doomed re-encryption. */
/* Kept for the clear_bonds() config command (still an empty stub on the Pico path). NOT called
   automatically any more -- see hog_discovery_timeout() for why unilaterally dropping our key
   behind the user's back is harmful. */
/* Forget EVERY bond, plus the "last connected device" tag. This is what the config tool's
   "Clear bonds" button does.
   NOTE the warning the tool must show the user: this clears OUR side only. The remote still holds
   ITS key, so it may think it already knows us -- accept the link, refuse to re-pair and refuse to
   serve GATT. Re-pair the REMOTE too, or you get a half-bond deadlock. (We learned this the hard
   way: it broke other, working firmware on the same remote.) */
static void ble_clear_all_bonds(void){
    int deleted = 0;
    int max = le_device_db_max_count();
    for (int i = 0; i < max; i++){
        int addr_type = BD_ADDR_TYPE_UNKNOWN;
        bd_addr_t addr;
        sm_key_t irk;
        le_device_db_info(i, &addr_type, addr, irk);
        if (addr_type == BD_ADDR_TYPE_UNKNOWN) continue;
        le_device_db_remove(i);
        deleted++;
    }
    btstack_tlv_get_instance(&btstack_tlv_singleton_impl, &btstack_tlv_singleton_context);
    if (btstack_tlv_singleton_impl){
        btstack_tlv_singleton_impl->delete_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD);
    }
    printf("   %d bond(s) cleared. NOTE: the REMOTE still holds its key -- re-pair it too.\n", deleted);
}

__attribute__((unused))
static void ble_forget_device(const bd_addr_t addr, bd_addr_type_t addr_type){
    // gap_delete_bonding() is the portable API. (This btstack has no
    // le_device_db_index_for_address.)
    gap_delete_bonding(addr_type, (uint8_t *) addr);
    printf("   bond for %s deleted\n", bd_addr_to_str((uint8_t *) addr));

    // also drop the "last connected device" tag, so the next boot scans instead of
    // going straight back to a device we just decided not to trust
    btstack_tlv_get_instance(&btstack_tlv_singleton_impl, &btstack_tlv_singleton_context);
    if (btstack_tlv_singleton_impl){
        btstack_tlv_singleton_impl->delete_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD);
    }
}

static bool adv_event_contains_hid_service(const uint8_t * packet){
    const uint8_t * ad_data = gap_event_advertising_report_get_data(packet);
    uint8_t ad_len = gap_event_advertising_report_get_data_length(packet);
    return ad_data_contains_uuid16(ad_len, ad_data, ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE);
}

/* WHY THE LED USED TO BLINK FOR AGES BEFORE CONNECTING.
   The BTstack example scans FOREVER waiting for an advertisement that carries the HID service
   UUID. A real BLE remote only puts that UUID (and its name) in the occasional advert -- most
   of its packets are bare -- and when it is asleep it may never send one. So we sat there
   skipping the device over and over.

   The fix (from shiomachisoft/picow_ble_usb_hid_bridge, which stays connected):
     * give scanning a DEADLINE, and when it expires connect straight to the BONDED address.
       A direct connect wakes the remote; it does not need to advertise at all.
     * make the connection timeout short (3s, not 10s) so a failed attempt is retried quickly
       instead of leaving the LED blinking for ten seconds.
     * ALWAYS remove a timer before re-adding it -- btstack_run_loop_add_timer asserts if the
       timer is already queued, which is easy to hit when a scan restarts mid-reconnect. */
#define CONNECTION_TIMEOUT_MS 3000
#define SCAN_TIMEOUT_MS       5000
/* HID discovery had NO deadline: hids_client_connect() would return OK and then the peer would
   simply never answer, leaving the firmware fast-blinking in silence forever -- the exact symptom
   on hardware. The cause is a STALE BOND: we reconnect and "Re-encryption complete, success", but
   the remote no longer honours that key for its GATT database, so it accepts the link and then
   ignores every discovery request. It is not recoverable by waiting.
   So: give discovery a deadline, and when it expires DELETE THE BOND and pair fresh. Self-healing;
   no need to put the remote into pairing mode by hand. (Clearing the bonds by hand is exactly what
   made it work the first time.) */
#define HID_DISCOVERY_TIMEOUT_MS 6000

static void ble_forget_device(const bd_addr_t addr, bd_addr_type_t addr_type);

/**
 * HID discovery went quiet. The bond is not trusted by the peer -- drop it and pair fresh.
 */
static void hog_discovery_timeout(btstack_timer_source_t * ts){
    UNUSED(ts);
    if (app_state != W4_HID_CLIENT_CONNECTED) return;
    printf("!! HID discovery timed out -- the peer accepted the link but will not serve its GATT db.\n");
    printf("   This is almost always the REMOTE, not us: a BLE HID device serves its HID service\n");
    printf("   to ONE bonded host. If it is still paired to a TV/phone, put it into pairing mode.\n");

    // DO NOT delete the bond here.
    //
    // An earlier version did, and it made things worse: deleting OUR key while the remote keeps
    // ITS key leaves a HALF BOND. The remote then thinks it already knows us, so it accepts the
    // link, refuses to re-pair, and refuses to serve GATT -- a deadlock that no firmware can get
    // out of, and which breaks other (working) firmware on the same remote too. The fix has to
    // happen on the remote (re-pair it), not by quietly desyncing the keys behind the user's back.
    app_state = W4_TIMEOUT_THEN_SCAN;
    if (connection_handle != HCI_CON_HANDLE_INVALID) {
        gap_disconnect(connection_handle);   // the disconnect handler restarts the scan
    } else {
        hog_start_connect();   // NOT _scan: that would make us pairable again
    }
}

/**
 * Scanning found nothing in time -> stop guessing and connect to the device we already know.
 */
static void hog_scan_timeout(btstack_timer_source_t * ts){
    UNUSED(ts);
    if (app_state != W4_HID_DEVICE_FOUND) return;
    printf("Scan timeout - trying a direct connect to the bonded device...\n");
    gap_stop_scan();
    hog_start_connect();
}

/**
 * Start scanning
 */
static void hog_start_scan(void){
    printf("Scanning for LE HID devices (timeout %dms)...\n", SCAN_TIMEOUT_MS);
    app_state = W4_HID_DEVICE_FOUND;

    btstack_run_loop_remove_timer(&connection_timer);   // may still be queued from a reconnect
    btstack_run_loop_set_timer(&connection_timer, SCAN_TIMEOUT_MS);
    btstack_run_loop_set_timer_handler(&connection_timer, &hog_scan_timeout);
    btstack_run_loop_add_timer(&connection_timer);

    // Active scanning, 100% (scan interval = scan window) -- also requests
    // scan responses so we see names/UUIDs for the diagnostic log below.
    gap_set_scan_parameters(1,48,48);
    gap_start_scan();
}

/**
 * Handle timeout for outgoing connection
 * @param ts
 */
static void hog_connection_timeout(btstack_timer_source_t * ts){
    UNUSED(ts);
    printf("Connection timeout - back to scanning\n");
    gap_connect_cancel();
    hog_start_connect();   // NOT _scan: that would make us pairable again
}


/**
 * Connect to remote device but set timer for timeout
 */
static void hog_connect(void) {
    printf("Connecting to %s (timeout %dms)...\n", bd_addr_to_str(remote_device.addr), CONNECTION_TIMEOUT_MS);

    btstack_run_loop_remove_timer(&connection_timer);   // the scan timeout may still be armed
    btstack_run_loop_set_timer(&connection_timer, CONNECTION_TIMEOUT_MS);
    btstack_run_loop_set_timer_handler(&connection_timer, &hog_connection_timeout);
    btstack_run_loop_add_timer(&connection_timer);

    app_state = W4_CONNECTED;
    gap_connect(remote_device.addr, remote_device.addr_type);
}

/**
 * Handle timer event to trigger reconnect
 * @param ts
 */
static void hog_reconnect_timeout(btstack_timer_source_t * ts){
    UNUSED(ts);
    switch (app_state){
        case W4_TIMEOUT_THEN_RECONNECT:
            hog_connect();
            break;
        case W4_TIMEOUT_THEN_SCAN:
            // NOT hog_start_scan(): that would make us pairable again. Go through
            // hog_start_connect(), which reconnects to the KNOWN device, and only scans if a
            // pairing window is actually open.
            hog_start_connect();
            break;
        default:
            break;
    }
}

/**
 * Start connecting after boot up: connect to last used device if possible, start scan otherwise
 */
static void hog_start_connect(void){
    // check if we have a bonded device
    btstack_tlv_get_instance(&btstack_tlv_singleton_impl, &btstack_tlv_singleton_context);
    if (btstack_tlv_singleton_impl){
        int len = btstack_tlv_singleton_impl->get_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD, (uint8_t *) &remote_device, sizeof(remote_device));
        if (len == sizeof(remote_device)){
            printf("Bonded, connect to device with %s address %s ...\n", remote_device.addr_type == 0 ? "public" : "random" , bd_addr_to_str(remote_device.addr));
            hog_connect();
            return;
        }
    }

    /* NO BOND -> we are pairable. This is first-time setup, and it is the ONLY time we go looking
       for a device we do not already know.
     *
     * The security question the owner asked was: "if the remote disconnects, is it open to anything
     * in the room?" The answer is NO -- and the reason is the branch ABOVE, not this one. Once a
     * device is bonded we ONLY ever reconnect to that device; a remote that is switched off or out
     * of range leaves the bond intact, so we sit there retrying it and will not touch anything else.
     *
     * An EARLIER version of this made a bond-less device sit idle and refuse to scan at all. That
     * bought no safety whatsoever (a device with no bond has nothing to protect) and it broke the
     * one thing that worked: a fresh remapper could never pair with anything, ever.
     *
     * So the rule is simply:
     *   bonded      -> reconnect to that device, and ONLY that device. Never pair with anything.
     *   not bonded  -> pairable (first-time setup, or right after "Pair new device"/"Clear bonds").
     */
    if (!pairing_mode) {
        printf("No bonded device -- looking for one to pair with (first-time setup).\n");
    }
    hog_start_scan();
}

/**
 * In case of error, disconnect and start scanning again
 */
static void handle_outgoing_connection_error(void){
    printf("Error occurred, disconnect and start over\n");
    gap_disconnect(connection_handle);
    hog_start_connect();   // NOT _scan: that would make us pairable again
}

/**
 * Handle GATT Client Events dependent on current state
 *
 * @param packet_type
 * @param channel
 * @param packet
 * @param size
 */
static void handle_gatt_client_event(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size) {
    UNUSED(packet_type);
    UNUSED(channel);
    UNUSED(size);

    uint8_t status;

    if (hci_event_packet_get_type(packet) != HCI_EVENT_GATTSERVICE_META){
        return;
    }
    
    switch (hci_event_gattservice_meta_get_subevent_code(packet)){
        case GATTSERVICE_SUBEVENT_HID_SERVICE_CONNECTED:
            status = gattservice_subevent_hid_service_connected_get_status(packet);
            switch (status){
                case ERROR_CODE_SUCCESS:
                    // discovery succeeded -- disarm the deadline, or it would delete a good bond
                    btstack_run_loop_remove_timer(&connection_timer);
                    ble_exit_pairing_mode();   // we have our device; stop accepting new ones
                    printf("HID service client connected, found %d services\n",
                        gattservice_subevent_hid_service_connected_get_num_instances(packet));

                    /* Hand the remote's HID REPORT DESCRIPTOR to core 0. This is what teaches the
                       engine what the remote's bytes MEAN -- it becomes "their descriptor", exactly
                       as a wired USB device's descriptor does. (We still present hid-remapper's OWN
                       descriptor to the PC; that is the whole point of remapping.) */
                    {
                        uint16_t dlen = hids_client_descriptor_storage_get_descriptor_len(hids_cid, 0);
                        const uint8_t * ddata = hids_client_descriptor_storage_get_descriptor_data(hids_cid, 0);
                        if ((ddata != NULL) && (dlen > 0)) {
                            printf("HID report descriptor: %u bytes -> engine\n", dlen);
                            ble_bridge_set_descriptor(ddata, dlen);
                        } else {
                            printf("!! no HID report descriptor from the device (len=%u)\n", dlen);
                        }
                    }

                                        // store device as bonded
                    if (btstack_tlv_singleton_impl){
                        btstack_tlv_singleton_impl->store_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD, (const uint8_t *) &remote_device, sizeof(remote_device));
                    }
                    // done
                    printf("Ready - please start typing or mousing..\n");
                    app_state = READY;
                    break;
                default:
                    printf("HID service client connection failed, status 0x%02x.\n", status);
                    handle_outgoing_connection_error();
                    break;
            }
            break;

        case GATTSERVICE_SUBEVENT_HID_SERVICE_DISCONNECTED:
            printf("HID service client disconnected\n");
            hog_start_connect();
            break;

        case GATTSERVICE_SUBEVENT_HID_REPORT:
            hid_handle_input_report(
                gattservice_subevent_hid_report_get_service_index(packet),
                gattservice_subevent_hid_report_get_report(packet), 
                gattservice_subevent_hid_report_get_report_len(packet));
            break;

        default:
            break;
    }
}

/* LISTING_START(packetHandler): Packet Handler */
static void packet_handler (uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size){
    /* LISTING_PAUSE */
    UNUSED(channel);
    UNUSED(size);
    uint8_t event;
    /* LISTING_RESUME */
    switch (packet_type) {
        case HCI_EVENT_PACKET:
            event = hci_event_packet_get_type(packet);
            switch (event) {
                case BTSTACK_EVENT_STATE:
                    if (btstack_event_state_get_state(packet) != HCI_STATE_WORKING) break;
                    btstack_assert(app_state == W4_WORKING);
                    
                    hog_start_connect();
                    break;
                case GAP_EVENT_ADVERTISING_REPORT:
                    if (app_state != W4_HID_DEVICE_FOUND) break;
                    {
                        bd_addr_t _a;
                        gap_event_advertising_report_get_address(packet, _a);
                        bool has_hid = adv_event_contains_hid_service(packet);

                        // Log the advertised NAME as well as the address. Without it every device is
                        // an anonymous MAC and you cannot tell which one is yours -- and the HID
                        // flag is useless for picking: on a real desk, 6 of 7 devices advertise
                        // hid=0 (including remotes that ARE HID devices), and the one that sets it
                        // may be a stranger's keyboard.
                        char name[32] = "";
                        adv_event_get_name(packet, name, sizeof(name));
                        printf("Adv %s  hid=%d  rssi=%d  name=\"%s\"\n",
                               bd_addr_to_str(_a), (int) has_hid,
                               (int) (int8_t) gap_event_advertising_report_get_rssi(packet), name);

                        // WHICH DEVICE DO WE CONNECT TO?
                        //   * If a target address is set, ONLY that device. (This is the general
                        //     mechanism: the web tool will set it after you pick from a scan list.
                        //     It is not tied to any one product.)
                        //   * Otherwise fall back to "advertises the HID UUID", which is what the
                        //     BTstack example does -- and which misses most real devices.
                        if (ble_has_target_addr()) {
                            if (!ble_addr_matches_target(_a)) break;
                            printf("Target matched.\n");
                        } else if (!has_hid) {
                            break;
                        }
                    }
                    // stop scan
                    gap_stop_scan();
                    // store remote device address and type
                    gap_event_advertising_report_get_address(packet, remote_device.addr);
                    remote_device.addr_type = gap_event_advertising_report_get_address_type(packet);
                    // connect
                    printf("Found, connect to device with %s address %s ...\n", remote_device.addr_type == 0 ? "public" : "random" , bd_addr_to_str(remote_device.addr));
                    hog_connect();
                    break;
                case HCI_EVENT_DISCONNECTION_COMPLETE: {
                    // BUG (fixed): this used to `break` unless app_state == READY, which made the
                    // `default:` arm below dead code. A link that dropped while CONNECTING or
                    // during HID DISCOVERY was therefore silently ignored -- the firmware sat
                    // there fast-blinking forever with a stale connection handle. Handle it in
                    // every state.
                    uint8_t reason = hci_event_disconnection_complete_get_reason(packet);
                    // 0x08 = supervision timeout (link lost / out of range / device slept)
                    // 0x13 = remote terminated   0x16 = local terminated   0x3e = failed to establish
                    printf("\nDisconnected (reason 0x%02x)", reason);
                    connection_handle = HCI_CON_HANDLE_INVALID;
                    switch (app_state){
                        case READY:
                            printf(" - reconnecting...\n");
                            app_state = W4_TIMEOUT_THEN_RECONNECT;
                            break;
                        default:
                            printf(" while %s - starting over...\n",
                                   app_state == W4_HID_CLIENT_CONNECTED ? "discovering the HID service"
                                 : app_state == W4_ENCRYPTED             ? "pairing"
                                 : app_state == W4_CONNECTED             ? "connecting"
                                                                         : "scanning");
                            app_state = W4_TIMEOUT_THEN_SCAN;
                            break;
                    }
                    // set timer (remove first: a scan/connection timeout may still be queued,
                    // and btstack_run_loop_add_timer asserts on an already-queued timer)
                    btstack_run_loop_remove_timer(&connection_timer);
                    btstack_run_loop_set_timer(&connection_timer, 100);
                    btstack_run_loop_set_timer_handler(&connection_timer, &hog_reconnect_timeout);
                    btstack_run_loop_add_timer(&connection_timer);
                    break;
                }
                case HCI_EVENT_META_GAP:
                    // wait for connection complete
                    if (hci_event_gap_meta_get_subevent_code(packet) != GAP_SUBEVENT_LE_CONNECTION_COMPLETE) break;
                    if (app_state != W4_CONNECTED) return;
                    btstack_run_loop_remove_timer(&connection_timer);
                    connection_handle = gap_subevent_le_connection_complete_get_connection_handle(packet);
                    // request security
                    app_state = W4_ENCRYPTED;
                    sm_request_pairing(connection_handle);
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
}
/* LISTING_END */

/* @section HCI packet handler
 *
 * @text The SM packet handler receives Security Manager Events required for pairing.
 * It also receives events generated during Identity Resolving
 * see Listing SMPacketHandler.
 */

/* LISTING_START(SMPacketHandler): Scanning and receiving advertisements */

static void sm_packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size){
    UNUSED(channel);
    UNUSED(size);

    if (packet_type != HCI_EVENT_PACKET) return;

    bool connect_to_service = false;

    switch (hci_event_packet_get_type(packet)) {
        case SM_EVENT_JUST_WORKS_REQUEST:
            printf("Just works requested\n");
            sm_just_works_confirm(sm_event_just_works_request_get_handle(packet));
            break;
        case SM_EVENT_NUMERIC_COMPARISON_REQUEST:
            printf("Confirming numeric comparison: %"PRIu32"\n", sm_event_numeric_comparison_request_get_passkey(packet));
            sm_numeric_comparison_confirm(sm_event_passkey_display_number_get_handle(packet));
            break;
        case SM_EVENT_PASSKEY_DISPLAY_NUMBER:
            printf("Display Passkey: %"PRIu32"\n", sm_event_passkey_display_number_get_passkey(packet));
            break;
        case SM_EVENT_PAIRING_COMPLETE:
            switch (sm_event_pairing_complete_get_status(packet)){
                case ERROR_CODE_SUCCESS:
                    printf("Pairing complete, success\n");
                    connect_to_service = true;
                    break;
                case ERROR_CODE_CONNECTION_TIMEOUT:
                    printf("Pairing failed, timeout\n");
                    break;
                case ERROR_CODE_REMOTE_USER_TERMINATED_CONNECTION:
                    printf("Pairing failed, disconnected\n");
                    break;
                case ERROR_CODE_AUTHENTICATION_FAILURE:
                    printf("Pairing failed, reason = %u\n", sm_event_pairing_complete_get_reason(packet));
                    break;
                default:
                    break;
            }
            break;
        case SM_EVENT_REENCRYPTION_COMPLETE:
            printf("Re-encryption complete, success\n");
            connect_to_service = true;
            break;
        default:
            break;
    }

    if (connect_to_service){
        // continue - query primary services
        printf("Search for HID service.\n");
        app_state = W4_HID_CLIENT_CONNECTED;
        // NEVER ignore this status. It used to be discarded, so when the call failed we printed
        // "Search for HID service." and hung forever with no clue why. It fails with
        // BTSTACK_MEMORY_ALLOC_FAILED when MAX_NR_HIDS_CLIENTS is not defined in btstack_config.h.
        uint8_t status = hids_client_connect(connection_handle, handle_gatt_client_event, protocol_mode, &hids_cid);
        if (status != ERROR_CODE_SUCCESS){
            // 0x56 = BTSTACK_MEMORY_ALLOC_FAILED -> the HIDS client pool is empty, i.e.
            // MAX_NR_HIDS_CLIENTS is missing from btstack_config.h.
            printf("!! hids_client_connect FAILED, status = 0x%02x (0x56 = out of memory: check MAX_NR_HIDS_CLIENTS)\n", status);
            app_state = W4_HID_DEVICE_FOUND;
            gap_disconnect(connection_handle);
        } else {
            printf("hids_client_connect OK, discovering HID service (timeout %dms)...\n", HID_DISCOVERY_TIMEOUT_MS);
            // Arm the deadline. Without it, a peer that accepts the link but ignores GATT leaves
            // us fast-blinking in silence forever -- there is nothing else in this state to
            // print, so the firmware just looks dead.
            btstack_run_loop_remove_timer(&connection_timer);
            btstack_run_loop_set_timer(&connection_timer, HID_DISCOVERY_TIMEOUT_MS);
            btstack_run_loop_set_timer_handler(&connection_timer, &hog_discovery_timeout);
            btstack_run_loop_add_timer(&connection_timer);
        }
    }
}
/* LISTING_END */

void ble_host_init(void){
    // Build-time target, e.g. -DBLE_TARGET_ADDR="68:FC:CA:B4:43:B7".
    // At runtime the web tool will call ble_host_set_target_addr() with whatever device you
    // picked from the scan list -- this define just lets us test without the UI in place.
#ifdef BLE_TARGET_ADDR
    ble_host_set_target_addr(BLE_TARGET_ADDR);
#endif


    if (cyw43_arch_init()) { printf("cyw43_arch_init failed\n"); return; }
    printf("init: cyw43 ok\n"); sleep_ms(60);

    /* LISTING_START(HogBootHostSetup): HID-over-GATT Host Setup */

    l2cap_init();
    printf("init: l2cap\n"); sleep_ms(60);

    // setup SM: Display only
    sm_init();
    sm_set_io_capabilities(IO_CAPABILITY_DISPLAY_ONLY);
    sm_set_authentication_requirements(SM_AUTHREQ_SECURE_CONNECTION | SM_AUTHREQ_BONDING);
    printf("init: sm\n"); sleep_ms(60);

    //
    gatt_client_init();
    printf("init: gatt_client\n"); sleep_ms(60);

    // setup ATT server - only needed if LE Peripheral does ATT queries on its own, e.g. Android and iOS
    att_server_init(profile_data, NULL, NULL);
    printf("init: att_server\n"); sleep_ms(60);

    hids_client_init(hid_descriptor_storage, sizeof(hid_descriptor_storage));
    printf("init: hids_client\n"); sleep_ms(60);

    // -DBLE_CLEAR_BONDS=ON -> forget every bond at boot, so we PAIR FRESH instead of
    // re-encrypting a bond the peer may no longer honour. The hardware log showed
    // "Re-encryption complete, success" and then HID discovery hanging forever -- a stale bond
    // is the prime suspect for a peer that accepts the link but will not serve its GATT db.
#ifdef BLE_CLEAR_BONDS
    {
        int deleted = 0;
        int max = le_device_db_max_count();
        for (int i = 0; i < max; i++){
            int addr_type = BD_ADDR_TYPE_UNKNOWN;
            bd_addr_t addr;
            sm_key_t irk;
            le_device_db_info(i, &addr_type, addr, irk);
            if (addr_type == BD_ADDR_TYPE_UNKNOWN) continue;
            le_device_db_remove(i);
            deleted++;
        }
        // also drop the "last connected device" tag so we do not try to reconnect to it
        btstack_tlv_get_instance(&btstack_tlv_singleton_impl, &btstack_tlv_singleton_context);
        if (btstack_tlv_singleton_impl){
            btstack_tlv_singleton_impl->delete_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD);
        }
        printf("init: BONDS CLEARED (%d) -- will pair fresh\n", deleted); sleep_ms(60);
    }
#endif

    // register for events from HCI
    hci_event_callback_registration.callback = &packet_handler;
    hci_add_event_handler(&hci_event_callback_registration);

    // register for events from Security Manager
    sm_event_callback_registration.callback = &sm_packet_handler;
    sm_add_event_handler(&sm_event_callback_registration);

    // DO NOT call sm_set_authentication_requirements() again here.
    //
    // This second call USED TO BE HERE, and it silently overwrote the one above -- dropping
    // SM_AUTHREQ_SECURE_CONNECTION and leaving only SM_AUTHREQ_BONDING. The result: we paired
    // with LEGACY, unauthenticated Just Works. Pairing "succeeded"... and then the remote
    // refused to serve its HID characteristics, because they require a properly secured link.
    // The peer accepted the connection and ignored every GATT request, so HID discovery went
    // silent and the LED blinked forever with nothing in the log.
    //
    // The upstream example this file came from has this line commented out. We did not.
    // (shiomachisoft/picow_ble_usb_hid_bridge keeps it commented, and it works.)
    // The correct requirements are set once, above:
    //     sm_set_authentication_requirements(SM_AUTHREQ_SECURE_CONNECTION | SM_AUTHREQ_BONDING);
    printf("init: handlers\n"); sleep_ms(60);

    /* LISTING_END */

    // Disable stdout buffering
	setvbuf(stdin, NULL, _IONBF, 0);

    app_state = W4_WORKING;

    // onboard LED status (Adapt E): reflects app_state going forward.
    btstack_run_loop_set_timer_handler(&led_timer, &led_timer_handler);
    btstack_run_loop_set_timer(&led_timer, 100);
    btstack_run_loop_add_timer(&led_timer);
    printf("init: led timer\n"); sleep_ms(60);

    // Turn on the device
    hci_power_control(HCI_POWER_ON);
    printf("init: hci_power_on -> entering run loop\n"); sleep_ms(60);
}

void ble_host_run(void) {
    btstack_run_loop_execute();
}

/* CORE 1 entry point. btstack_run_loop_execute() never returns -- which is exactly why BTstack gets
   a core to itself, leaving core 0 free to run hid-remapper's engine and the USB device stack.
   (shiomachisoft/picow_ble_usb_hid_bridge does the same, and it is proven on this hardware.) */
void ble_host_main(void) {
    // Let core 0 freeze us while it erases flash to save the config -- we execute FROM flash, so
    // without this we would be fetching instructions from a chip that has stopped answering.
    multicore_lockout_victim_init();

    ble_host_init();
    ble_host_run();
}

/* EXAMPLE_END */
